config/routes.rb
Rails.application.routes.draw do
  root to: 'tweets#index'
  resources :tweets do
    resource :like
    resource :retweet
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    after_initialize :set_defaults, unless: :persisted?
    # The set_defaults will only work if the object is new
    
    validates :title, presence: true

    after_create_commit { broadcast_prepend_to 'tweets' }
    after_update_commit { broadcast_replace_to 'tweets' }
    after_destroy_commit { broadcast_remove_to 'tweets' }

    def set_defaults
        self.likesCount = 0
        self.retweetsCount = 0
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :set_tweet

    def create
        @tweet.increment! :likesCount
        redirect_to @tweet
    end

    private

    def set_tweet
        @tweet = Tweet.find(params[:tweet_id])
    end
end

app/controllers/retweets_controller.rb
class RetweetsController < ApplicationController
    before_action :set_tweet

    def create
        @tweet.increment! :retweetsCount
        redirect_to @tweet
    end


    private

    def set_tweet
        @tweet = Tweet.find(params[:tweet_id])
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all
    @tweet = Tweet.new
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_url, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.turbo_stream {render turbo_stream: turbo_stream.replace(@tweet, partial: "tweets/form", locals: {tweet: @tweet})}
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:title, :likesCount, :retweetsCount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweeter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

  <body>
    <div class="container bg-dark text-light">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, id: dom_id(tweet)) do |form| %>

  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibieron este tweet de ser creado:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, :class => 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Tweet', :class => 'btn btn-primary mt-2' %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<%= turbo_frame_tag dom_id(tweet) do %>
 <div class="card m-4 bg-secondary">
   <div class="card-content">
        <h5><%= tweet.title %></h5>
        <div class="btn-group">
            <%= button_to "Like #{tweet.likesCount}", tweet_like_path(tweet), method: :post, class: "btn btn-primary btn-sm m-1" %>
            <%= button_to "Retweet #{tweet.retweetsCount}", tweet_retweet_path(tweet), method: :post, class: "btn btn-success btn-sm m-1" %>
            <%= button_to "Editar", edit_tweet_path(tweet), method: :get, :class => "btn btn-danger btn-sm m-1" %>
            <%= button_to "Eliminar", tweet, method: :delete, :class => "btn btn-danger btn-sm m-1" %>
        </div>
   </div>
 </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= turbo_frame_tag dom_id(@tweet) do %>
  <div class="card m-4 bg-secondary">
    <div class="card card-content">
      <%= render 'form', tweet: @tweet %> 
      <%= button_to 'Cancel', @tweet, method: :get, :class => "btn btn-danger btn-sm m-1" %>
    </div>
  </div>
<% end %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<%= turbo_stream_from 'tweets' %>

<%= turbo_frame_tag 'tweet_form' do %>
  <%= render 'form', tweet: @tweet %>
<% end %>

<%= turbo_frame_tag 'tweets' do %>
  <%= render @tweets %>
<% end %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<%= turbo_frame_tag dom_id(@tweet) do %>
  <%= render @tweet %>
<% end %>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>